### ISSUE TITLE
RAND() is CPU-bound

### ISSUE THREAD

**Issue by isodude** [odan/benchmark-php#6]
Introduced in https://github.com/odan/benchmark-php/commit/f88a374a37a1b6797bbfa3f46ad6369558ff683e the mysql query now uses RAND.

Doing that many calls to RAND is heavily CPU bound and generates at least 7 seconds on the benchmark test, which dwarfs the other metrics by far. 

I feel that this i skewing the result quite a bit.

**Comment by odan** [comment]
That's the idea behind a benchmark :-) If you don't want to test the database, just comment out the  database settings. 

```php
//$options['db.host'] = '127.0.0.1';
```
